# -*- coding: utf-8 -*-
"""
Created on Thu Oct  7 12:39:49 2021

@author: Stefano Angelo Rizzo

NB: è un metodo brutto, aggiungere cose nuove sarà un delirio, ma di base dopo che metti tutto nel formato corretto basta fare un append alla lista di liste x, oppure inserire manualmente se le cose son poche.

"""

x = [["Repositorio della DMI", "https://wiki.digitalmethods.net/Dmi/ToolDatabase", "Database di strumenti utili al web scraping (tra cui forum e siti di uso comune come Wikipedia, Twitter, Facebook e YouTube) a cura della Digital Methods Initiative", "Gratuito"],
["Keyhole.co", "https://keyhole.co/", "Permette la ricerca di hashtag e parole chiave su Instagram e Twitter", "A pagamento, con prova gratuita"],
["BuzzSumo", "BuzzSumo.com", "Permette il monitoraggio di alcune parole chiave in un dato intervallo di tempo e in degli URL impostabili", "A pagamento, con prova gratuita"],
["TweetReach", "https://tweetreach.com/", "Permette il monitoraggio di account Twitter e della diffusione dei post", "A pagamento, con prova gratuita"],
["Topsy", "[offline due anni dopo l’acquisto di Apple]", "-", "-"],
["Google Ngram Viewer", "https://books.google.com/ngrams", "Permette la visualizzazione di N-grams nell’archivio di libri curato da Google", "Gratuito"],
["Google Trends", "https://trends.google.it/trends/?geo=IT", "Permette la visualizzazione degli argomenti di ricerca effettuati maggiormente sul motore di ricerca Google, anche in un intervallo di tempo o geografico", "Gratuito"],
["Google Analytics", "https://analytics.google.com/analytics/web/provision/#/provision", "Servizio di web analysis offerto da Google, utile per monitorare il traffico di un proprio sito web", "Gratuito"],
["Gephi", "https://gephi.org/", "Programma per la visualizzazione e la presentazione a un pubblico di dati", "Gratuito e open source"],
["Notepad++", "https://notepad-plus-plus.org/downloads/", "Una versione migliore del caro vecchio Notepad, con integrazioni utili alla data analysis e ai formati HTML / CSS", "Gratuito"],
["LinkedIn InMaps tool", "[offline]", "-", "-"],
["Zotero", "https://www.zotero.org/", "Strumento per l’organizzazione delle fonti", "Gratuito ma con possibilità di espansioni a pagamento"],
["Mendeley", "https://www.mendeley.com/download-desktop-new/", "Strumento per l’organizzazione delle fonti", "Gratuito ma con possibilità di espansioni a pagamento"],
["CiteULike", "[offline]", "-", "-"],
["Facebook Graph Search", "[evoluto in Facebook Search]", "-", "-"],
["Facebook Search", "[evoluto nell’algoritmo Rosetta]", "-", "-"],
["Mapping for Change", "https://mappingforchange.org.uk/", "Repositorio di mappe topiche fatte dagli utenti e di case study", "Accesso gratuito alle mappe già presenti"],
["Micro Mappers", "https://micromappers.wordpress.com/maps/", "Repositorio di mappe topiche fatte dagli utenti e di case study", "Accesso gratuito alle mappe già presenti"],
["Open Street Map", "www.openstreetmap.org", "Mappa editabile ed esportabile", "Gratuito, previa registrazione"],
["SNAP Stanford", "http://snap.stanford.edu/", "Dataset e programmi per l’analisi di network sociali", "Gratuito"],
["Inside Airbnb", "http://insideairbnb.com/get-the-data.html", "Dataset sul sito Airbnb", "Gratuito"],
["Netlytic", "https://netlytic.org/index.php", "Strumento per l’estrazione di dati da social media", "Gratuito, previa registrazione, con possibilità di espansioni a pagamento"],
["Tool sviluppati da Bernhard Rieder", "http://labs.polsys.net/tools/", "Lista di tool per l’estrazione di dati da vari siti, tra i quali Amazon, Tumblr, Reddit", "Gratuito"],
["Data Scraper", "https://chrome.google.com/webstore/detail/data-scraper-easy-web-scr/nndknepjnldbdbepjfgmncbggmopgden", "Estensione per Google Chrome per l’estrazione di dati", "Gratuito"],
["Data Miner", "https://dataminer.io/", "Estensione per Edge per l’estrazione di dati", "Gratuito"],
["Facebook Graph API", "https://developers.facebook.com/docs/graph-api/", "API per l’estrazione di social graph su Facebook", "Gratuito"],
["Facebook Marketing API", "https://developers.facebook.com/docs/marketing-apis/", "API per l’estrazione di dati commerciali su Facebook", "Gratuito"],
["Twitter API", "https://developer.twitter.com/en/docs", "API per l’estrazione di dati su Twitter (e sul comparto Ads)", "Gratuito"],
["Isntagram Basic Display API", "https://developers.facebook.com/docs/instagram-basic-display-api", "API per l’estrazione di dati da Instagram", "Gratuito"],
["Instagram Graph API", "https://developers.facebook.com/docs/instagram-api/", "API per l’estrazione di social graph da Instagram", "Gratuito"],
["TouchGraph", "https://www.touchgraph.com/navigator", "Tool per la triangolazione di network relazionali online", "A pagamento, con prova gratuita"],
["Tutorial Contextures su tabelle pivot di Excel", "https://www.contextures.com/createpivottable.html", "Guida fatta da Contextures su come creare tabelle pivot su Excel, utili a incrociare dati raccolti	", "Gratuito"],
["Force Atlas 2", "https://github.com/gephi/gephi/wiki/Force-Atlas-2", "Algoritmo di visualizzazione per la network analysis in Gephi", "Gratuito"],
["NodeXL", "https://www.smrfoundation.org/nodexl/", "Software di visualizzazione per la network analysis", "A pagamento"],
["SocioViz	", "https://socioviz.net/", "Servizio di social network analysis", "Gratuito, previa iscrizione"],
["Netvizz", "[offline dal 2019 causa scandalo Cambridge Analytica]", "-", "-"],
["LexisNexis", "https://www.lexisnexis.com/en-us/home.page", "Database di documenti legali e giornalistici", "A pagamento, ma con possibilità di prova gratuita e di collaborazione gratuita per studenti"],
["WhatCMS.org", "https://whatcms.org/", "Servizio online che permette di scoprire quale CMS un sito internet di nostra scelta stia utilizzando", "Gratuito"],
["PowerMapper", "https://www.powermapper.com/products/mapper/try/", "Servizio online che permette di visualizzare la ramificazione delle pagine di un sito web", "Prova gratuita online"],
["Voyant Tools", "https://voyant-tools.org/", "Servizio online di studio del testo con una grande quantità di tool", "Gratuito"],
["LancsBox", "http://corpora.lancs.ac.uk/lancsbox/download.php", "Programma per l’analisi di corpus, gemello di Lancaster Stat Tool online", "Gratuito"],
["Lancaster Stat Tool online", "http://corpora.lancs.ac.uk/stats/toolbox.php", "Tool online per l’analisi di dati statistici ottenuti da un corpus, gemello di LancsBox", "Gratuito"],
["T-Lab", "https://www.tlab.it/download/", "Software per l’analisi semi automatica di testi", "Gratuito, previa registrazione, con possibilità di espansioni a pagamento"],
["Repositorio Giat di software", "http://www.giat.org/?page_id=16&lang=it", "Repositorio online di tools per l’analisi di testi, con sezione dedicata a quelli in italiano", "Gratuito"],
["Alceste", "https://www.image-zafar.com/Logicieluk.html", "Software per l’analisi semi automatica di testi", "A pagamento"],
["Atlas.ti", "https://atlasti.com/", "Software per l’analisi computer-aided di dati testuali", "A pagamento, con prova gratuita anche online"],
["NVivo", "https://www.qsrinternational.com/nvivo-qualitative-data-analysis-software/try-nvivo", "Software per l’analisi computer-aided di dati testuali", "A pagamento, con prova gratuita"],
["Google Vision API", "https://cloud.google.com/vision/?hl=it&utm_source=google&utm_medium=cpc&utm_campaign=emea-it-all-it-dr-bkws-all-all-trial-e-gcp-1010042&utm_content=text-ad-none-any-DEV_c-CRE_170511603496-ADGP_Hybrid%20%7C%20BKWS%20-%20EXA%20%7C%20Txt%20~%20AI%20%26%20ML%20~%20Vision%20AI%23v1-KWID_43700053287028099-aud-606988878214%3Akwd-203288731687-userloc_1008279&utm_term=KW_google%20vision%20api-NET_g-PLAC_&gclid=CjwKCAjwn6GGBhADEiwAruUcKnrgiFTXSDv7FSwcjOpLwWfwu12W08EXj5oDESIkO7IApfYZ9E_51BoCQT4QAvD_BwE&gclsrc=aw.ds", "Servizio Google per il riconoscimento di contesti dalle immagini", "A pagamento, con prova gratuita"],
["Google Scholar", "https://scholar.google.com/", "Motore di ricerca di papers e tesi scientifiche", "Gratuito"],
["Google Books", "https://books.google.it/", "Motore di ricerca di testi integrali nel repositorio Google", "Gratuito"],
["All Our Ideas", "https://www.allourideas.org/", "Servizio online di creazione di wiki surveys", "Gratuito e open source"],
["Mturk", "https://www.mturk.com/get-started", "Servizio online di distribuzione di task utili alla ricerca sociale", "A pagamento"],
["Servizi di MySociety", "https://data.mysociety.org/", "Repositorio online di dati, specie sul Regno Unito, sull’attivismo civico e di API per il loro reperimento", "Gratuito"],
["Google Correlate", "[evoluto in Google Trends]", "-", "-"],
["Twitter Steamgraphs", "http://www.neoformix.com/Projects/TwitterStreamGraphs/view.php?q=coffee", "Creazione di grafici di andamenti di keyword su Twitter", "Gratuito (richiede Java)"],
["Gov.uk data", "https://data.gov.uk/", "Repositorio di dati sull’UK", "Gratuito"],
["Lettore di dati Tlex Suite", "http://tshwanedje.com/downloads/download.php?app=tlReader", "Lettore per dati lessicografici scritti usando la TLex Suite", "Gratuito"],
["Tlex Suite", "http://tshwanedje.com/store/", "Software per studi e output lessicografici", "A pagamento"],
["WordSmith tools", "https://lexically.net/wordsmith/downloads/", "Software per studi su corpus", "Gratuito, con possibilità di upgrade a pagamento"],
["MonoConc", "https://www.monoconc.com/", "Software per studi su corpus", "Gratuito, con possibilità di upgrade a pagamento"],
["AntConc", "https://www.laurenceanthony.net/software/antconc/", "Software per studi su corpus", "Gratuito"],
["SketchEngine", "https://auth.sketchengine.eu/#login", "Servizio online per studi su corpus", "Gratuito"],
["Korpus DK", "https://ordnet.dk/korpusdk_en?set_language=en", "Servizio online per studi su corpus", "Gratuito"],
["IMS Corpus Workbench", "https://cwb.sourceforge.io/install.php	", "Software per studi su corpus", "Gratuito"],
["Web Corp", "https://www.webcorp.org.uk/live/", "Servizio online per studi su corpus costruiti dal web", "Gratuito"],
["XAIRA", "https://sourceforge.net/projects/xaira/files/", "Programma per studi su corpus costruiti dal web", "Gratuito e open source"],
["Oxygen XML", "https://www.oxygenxml.com/xml_editor/register.html?p=editor", "Compilatore XML", "Prova gratuita"],
["Xmetal Author", "https://go.pardot.com/l/333831/2020-03-23/352xgn", "Compilatore XML", "Prova gratuita"],
["Servizi e tool per dizionari di Elexis", "https://elex.is/tools-and-services/", "Lista di servizi e tool per la creazione di dizionari a cura della Elexis", "Gratuito"],
["eLexico", "https://www.elexico.com/it/Tecnologia%20e%20supporto/1925922-1925977.html", "Servizio e tool autonomo per la creazione di dizionari", "A pagamento"],
["DWDS", "https://www.dwds.de/", "Servizio per l’analisi di lemmi tedeschi come entry di dizionario e come entry di corpora", "Gratuito"],
["DEB", "https://deb.fi.muni.cz/project.php", "Servizi e tool per la creazione di dizionari", "Gratuito previa registrazione"],
["TRAME project", "http://trame.fefonlus.it/trame/index.php", "Repositorio ricercabile online di corpus di testi e manoscritti medioevali", "Gratuito"],
["TLIO", "http://tlio.ovi.cnr.it/TLIO/", "Dizionario storico online della lingua italiana", "Gratuito"],
["Corpus OVI attraverso GATTO WEB", "http://gattoweb.ovi.cnr.it/(S(5jgoq4h0exu5fdcdcqgkro4q))/CatForm01.aspx", "Corpus online di testi dell’italiano antico", "Gratuito"],
["GATTO", "http://www.ovi.cnr.it/Installazione-GATTO.html", "Programma di gestione lessicografica di corpus", "Gratuito"],
["Banche dati della Lirica Medievale Romanza", "https://letteraturaeuropea.let.uniroma1.it/?q=databases", "Repositorio online di database interrogabili sulla lirica medievale romanza", "Gratuito"],
["Rialto", "http://www.rialto.unina.it/index.html", "Repositorio online di testi trobadorici", "Gratuito"],
["BEdT", "http://www.bedt.it/BEdT_04_25/index.aspx", "Repositorio online di testi trobadorici", "Gratuito, previa registrazione"],
["JGAAP", "https://github.com/evllabs/JGAAP", "Programma per analisi, categorizzazione e attribuzione di testi", "Gratuito"],
["Databases di Mirabile web", "http://mirabileweb.it/", "Repositorio online di database interrogabili sulla lirica mediolatina, romanza e agiografica", "Gratuito"],
["EEBO-TCP", "https://quod.lib.umich.edu/e/eebogroup/", "Repositorio ricercabile di antichi testi letterari inglesi", "Gratuito"],
["Repositorio di tool “Interedition”", "https://github.com/interedition", "Repositorio su GitHub di tool utili alle edizioni filologiche digitali", "Gratuito"],
["DocBook", "https://docbook.org/tools/", "Strumento di markup XML", "Gratuito"],
["LaTeX", "https://www.latex-project.org/get/", "Strumento di markup XML", "Gratuito"],
["CATMA", "https://app.catma.de/catma/", "Strumento di markup XML e di analisi di corpus", "Gratuito, previa registrazione"],
["Way Back Machine", "https://archive.org/web/" ,"Strumento di visualizzazione di pagine web nel tempo", "Gratuito"],
["Internet Archive", "https://archive.org/", "Repositorio online di libri, film, musica e software", "Gratuito"],
["Voyeur", "[evoluto in Voyant Tools]","-", "-"],
["Juxta", "https://www.juxtasoftware.org/download/", "Tool di supporto per la collezione ed il confronto di testi", "Gratuito"],
["Omeka Classic", "https://omeka.org/classic/", "Piattaforma di pubblicazione online utile per mostrare collezioni digitali", "Gratuito"],
["Libreria digitale Perseo", "http://www.perseus.tufts.edu/hopper/", "Repositorio in inglese di testi romani, greci, gallici, arabi, del 19esimo secolo, rinascimentali e di poesie italiane in latino", "Gratuito"],
["Biblioteca virtuale degli umanisti", "http://www.bvh.univ-tours.fr/", "Repositorio in francese di testi filologici", "Gratuito"],
["Tableau", "https://www.tableau.com/it-it/products/trial", "Tool di visualizzazione ed esplorazione di dati", "Prova gratuita"],
["Tableau public", "https://public.tableau.com/s/", "Tool di visualizzazione ed esplorazione di dati", "Gratuito, previa registrazione e circolazione libera del materiale"],
["Microsoft Power Bi", "https://powerbi.microsoft.com/it-it/getting-started-with-power-bi/", "Tool di visualizzazione ed esplorazione di dati", "Prova gratuita"]]

for list in x:
    print("")
    print("<tr>")
    print(" <th>", list[0], "</th>")
    print(" <td><a href=\"", list[1],"\"", "</a>SCARICA AL SEGUENTE INDIRIZZO</td>")
    print(" <td>", list[2], "</td>")
    print(" <td>", list[3], "</td>")
    print("</tr>")
    print("")